/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.asmetal.asmetaL.AnyDomain;
import org.xtext.asmetal.asmetaL.AsmetaLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Any Domain</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AnyDomainImpl extends TypeDomainImpl implements AnyDomain
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AnyDomainImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetaLPackage.Literals.ANY_DOMAIN;
  }

} //AnyDomainImpl
