/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.asmetal.asmetaL.AsmetaLPackage;
import org.xtext.asmetal.asmetaL.BasicTD;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Basic TD</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BasicTDImpl extends TypeDomainImpl implements BasicTD
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BasicTDImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetaLPackage.Literals.BASIC_TD;
  }

} //BasicTDImpl
