/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.asmetal.asmetaL.AsmetaLPackage;
import org.xtext.asmetal.asmetaL.BasicFunction;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Basic Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BasicFunctionImpl extends FunctionImpl implements BasicFunction
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BasicFunctionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetaLPackage.Literals.BASIC_FUNCTION;
  }

} //BasicFunctionImpl
