/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.asmetal.asmetaL.AsmetaLPackage;
import org.xtext.asmetal.asmetaL.basicExpr;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>basic Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class basicExprImpl extends ExpressionImpl implements basicExpr
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected basicExprImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetaLPackage.Literals.BASIC_EXPR;
  }

} //basicExprImpl
