/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.asmetal.asmetaL.AsmetaLPackage;
import org.xtext.asmetal.asmetaL.CharDomain;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Char Domain</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CharDomainImpl extends StandardDomainImpl implements CharDomain
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CharDomainImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetaLPackage.Literals.CHAR_DOMAIN;
  }

} //CharDomainImpl
