/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.asmetal.asmetaL.AsmetaLPackage;
import org.xtext.asmetal.asmetaL.ComplexDomain;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Complex Domain</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ComplexDomainImpl extends StandardDomainImpl implements ComplexDomain
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComplexDomainImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetaLPackage.Literals.COMPLEX_DOMAIN;
  }

} //ComplexDomainImpl
