/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.asmetal.asmetaL.AsmetaLPackage;
import org.xtext.asmetal.asmetaL.ControlledFunction;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Controlled Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ControlledFunctionImpl extends DynamicFunctionImpl implements ControlledFunction
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ControlledFunctionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetaLPackage.Literals.CONTROLLED_FUNCTION;
  }

} //ControlledFunctionImpl
