/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.asmetal.asmetaL.AsmetaLPackage;
import org.xtext.asmetal.asmetaL.DerivedRule;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Derived Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DerivedRuleImpl extends RuleImpl implements DerivedRule
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DerivedRuleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetaLPackage.Literals.DERIVED_RULE;
  }

} //DerivedRuleImpl
