/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.asmetal.asmetaL.AsmetaLPackage;
import org.xtext.asmetal.asmetaL.DomainTerm;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Domain Term</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DomainTermImpl extends TermImpl implements DomainTerm
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DomainTermImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetaLPackage.Literals.DOMAIN_TERM;
  }

} //DomainTermImpl
