/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.asmetal.asmetaL.AsmetaLPackage;
import org.xtext.asmetal.asmetaL.FairnessConstraint;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Fairness Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FairnessConstraintImpl extends MinimalEObjectImpl.Container implements FairnessConstraint
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FairnessConstraintImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetaLPackage.Literals.FAIRNESS_CONSTRAINT;
  }

} //FairnessConstraintImpl
