/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.asmetal.asmetaL.AsmetaLPackage;
import org.xtext.asmetal.asmetaL.ForallTerm;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Forall Term</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ForallTermImpl extends FiniteQuantificationTermImpl implements ForallTerm
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ForallTermImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetaLPackage.Literals.FORALL_TERM;
  }

} //ForallTermImpl
