/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.asmetal.asmetaL.AgentInitialization;
import org.xtext.asmetal.asmetaL.AsmetaLPackage;
import org.xtext.asmetal.asmetaL.DomainInitialization;
import org.xtext.asmetal.asmetaL.FunctionInitialization;
import org.xtext.asmetal.asmetaL.Initialization;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Initialization</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.asmetal.asmetaL.impl.InitializationImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.asmetal.asmetaL.impl.InitializationImpl#getDomainInitialization <em>Domain Initialization</em>}</li>
 *   <li>{@link org.xtext.asmetal.asmetaL.impl.InitializationImpl#getFunctionInitialization <em>Function Initialization</em>}</li>
 *   <li>{@link org.xtext.asmetal.asmetaL.impl.InitializationImpl#getAgentInitialization <em>Agent Initialization</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InitializationImpl extends MinimalEObjectImpl.Container implements Initialization
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getDomainInitialization() <em>Domain Initialization</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDomainInitialization()
   * @generated
   * @ordered
   */
  protected EList<DomainInitialization> domainInitialization;

  /**
   * The cached value of the '{@link #getFunctionInitialization() <em>Function Initialization</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFunctionInitialization()
   * @generated
   * @ordered
   */
  protected EList<FunctionInitialization> functionInitialization;

  /**
   * The cached value of the '{@link #getAgentInitialization() <em>Agent Initialization</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAgentInitialization()
   * @generated
   * @ordered
   */
  protected EList<AgentInitialization> agentInitialization;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InitializationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetaLPackage.Literals.INITIALIZATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AsmetaLPackage.INITIALIZATION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<DomainInitialization> getDomainInitialization()
  {
    if (domainInitialization == null)
    {
      domainInitialization = new EObjectContainmentEList<DomainInitialization>(DomainInitialization.class, this, AsmetaLPackage.INITIALIZATION__DOMAIN_INITIALIZATION);
    }
    return domainInitialization;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<FunctionInitialization> getFunctionInitialization()
  {
    if (functionInitialization == null)
    {
      functionInitialization = new EObjectContainmentEList<FunctionInitialization>(FunctionInitialization.class, this, AsmetaLPackage.INITIALIZATION__FUNCTION_INITIALIZATION);
    }
    return functionInitialization;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<AgentInitialization> getAgentInitialization()
  {
    if (agentInitialization == null)
    {
      agentInitialization = new EObjectContainmentEList<AgentInitialization>(AgentInitialization.class, this, AsmetaLPackage.INITIALIZATION__AGENT_INITIALIZATION);
    }
    return agentInitialization;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AsmetaLPackage.INITIALIZATION__DOMAIN_INITIALIZATION:
        return ((InternalEList<?>)getDomainInitialization()).basicRemove(otherEnd, msgs);
      case AsmetaLPackage.INITIALIZATION__FUNCTION_INITIALIZATION:
        return ((InternalEList<?>)getFunctionInitialization()).basicRemove(otherEnd, msgs);
      case AsmetaLPackage.INITIALIZATION__AGENT_INITIALIZATION:
        return ((InternalEList<?>)getAgentInitialization()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AsmetaLPackage.INITIALIZATION__NAME:
        return getName();
      case AsmetaLPackage.INITIALIZATION__DOMAIN_INITIALIZATION:
        return getDomainInitialization();
      case AsmetaLPackage.INITIALIZATION__FUNCTION_INITIALIZATION:
        return getFunctionInitialization();
      case AsmetaLPackage.INITIALIZATION__AGENT_INITIALIZATION:
        return getAgentInitialization();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AsmetaLPackage.INITIALIZATION__NAME:
        setName((String)newValue);
        return;
      case AsmetaLPackage.INITIALIZATION__DOMAIN_INITIALIZATION:
        getDomainInitialization().clear();
        getDomainInitialization().addAll((Collection<? extends DomainInitialization>)newValue);
        return;
      case AsmetaLPackage.INITIALIZATION__FUNCTION_INITIALIZATION:
        getFunctionInitialization().clear();
        getFunctionInitialization().addAll((Collection<? extends FunctionInitialization>)newValue);
        return;
      case AsmetaLPackage.INITIALIZATION__AGENT_INITIALIZATION:
        getAgentInitialization().clear();
        getAgentInitialization().addAll((Collection<? extends AgentInitialization>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AsmetaLPackage.INITIALIZATION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case AsmetaLPackage.INITIALIZATION__DOMAIN_INITIALIZATION:
        getDomainInitialization().clear();
        return;
      case AsmetaLPackage.INITIALIZATION__FUNCTION_INITIALIZATION:
        getFunctionInitialization().clear();
        return;
      case AsmetaLPackage.INITIALIZATION__AGENT_INITIALIZATION:
        getAgentInitialization().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AsmetaLPackage.INITIALIZATION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case AsmetaLPackage.INITIALIZATION__DOMAIN_INITIALIZATION:
        return domainInitialization != null && !domainInitialization.isEmpty();
      case AsmetaLPackage.INITIALIZATION__FUNCTION_INITIALIZATION:
        return functionInitialization != null && !functionInitialization.isEmpty();
      case AsmetaLPackage.INITIALIZATION__AGENT_INITIALIZATION:
        return agentInitialization != null && !agentInitialization.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //InitializationImpl
