/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.asmetal.asmetaL.AsmetaLPackage;
import org.xtext.asmetal.asmetaL.IntegerDomain;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Integer Domain</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class IntegerDomainImpl extends StandardDomainImpl implements IntegerDomain
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IntegerDomainImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetaLPackage.Literals.INTEGER_DOMAIN;
  }

} //IntegerDomainImpl
