/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.asmetal.asmetaL.AsmetaLPackage;
import org.xtext.asmetal.asmetaL.LtlSpec;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Ltl Spec</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class LtlSpecImpl extends TemporalPropertyImpl implements LtlSpec
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LtlSpecImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetaLPackage.Literals.LTL_SPEC;
  }

} //LtlSpecImpl
