/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.asmetal.asmetaL.AsmetaLPackage;
import org.xtext.asmetal.asmetaL.MacroDeclaration;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Macro Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MacroDeclarationImpl extends RuleDeclarationImpl implements MacroDeclaration
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MacroDeclarationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetaLPackage.Literals.MACRO_DECLARATION;
  }

} //MacroDeclarationImpl
