/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.asmetal.asmetaL.AsmetaLPackage;
import org.xtext.asmetal.asmetaL.ReserveDomain;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Reserve Domain</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ReserveDomainImpl extends AbstractTDImpl implements ReserveDomain
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ReserveDomainImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetaLPackage.Literals.RESERVE_DOMAIN;
  }

} //ReserveDomainImpl
