/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.asmetal.asmetaL.AsmetaLPackage;
import org.xtext.asmetal.asmetaL.SequenceCT;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sequence CT</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SequenceCTImpl extends ComprehensionTermImpl implements SequenceCT
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SequenceCTImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetaLPackage.Literals.SEQUENCE_CT;
  }

} //SequenceCTImpl
