/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.asmetal.asmetaL.AsmetaLPackage;
import org.xtext.asmetal.asmetaL.StandardDomain;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Standard Domain</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class StandardDomainImpl extends BasicTDImpl implements StandardDomain
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StandardDomainImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetaLPackage.Literals.STANDARD_DOMAIN;
  }

} //StandardDomainImpl
