/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.asmetal.asmetaL.AsmetaLPackage;
import org.xtext.asmetal.asmetaL.StaticFunction;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Static Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class StaticFunctionImpl extends BasicFunctionImpl implements StaticFunction
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StaticFunctionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetaLPackage.Literals.STATIC_FUNCTION;
  }

} //StaticFunctionImpl
