/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.asmetal.asmetaL.AsmetaLPackage;
import org.xtext.asmetal.asmetaL.StructuredTD;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Structured TD</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class StructuredTDImpl extends TypeDomainImpl implements StructuredTD
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StructuredTDImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetaLPackage.Literals.STRUCTURED_TD;
  }

} //StructuredTDImpl
