/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.asmetal.asmetaL.AsmetaLPackage;
import org.xtext.asmetal.asmetaL.TemporalProperty;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Temporal Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TemporalPropertyImpl extends PropertyImpl implements TemporalProperty
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TemporalPropertyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetaLPackage.Literals.TEMPORAL_PROPERTY;
  }

} //TemporalPropertyImpl
