/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.asmetal.asmetaL.AsmetaLPackage;
import org.xtext.asmetal.asmetaL.TurboRule;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Turbo Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TurboRuleImpl extends RuleImpl implements TurboRule
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TurboRuleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetaLPackage.Literals.TURBO_RULE;
  }

} //TurboRuleImpl
