/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.asmetal.asmetaL.AsmetaLPackage;
import org.xtext.asmetal.asmetaL.TurboDeclaration;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Turbo Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TurboDeclarationImpl extends RuleDeclarationImpl implements TurboDeclaration
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TurboDeclarationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetaLPackage.Literals.TURBO_DECLARATION;
  }

} //TurboDeclarationImpl
