/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.asmetal.asmetaL.AsmetaLPackage;
import org.xtext.asmetal.asmetaL.UndefDomain;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Undef Domain</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class UndefDomainImpl extends StandardDomainImpl implements UndefDomain
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UndefDomainImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetaLPackage.Literals.UNDEF_DOMAIN;
  }

} //UndefDomainImpl
