/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.asmetal.asmetaL.AsmetaLPackage;
import org.xtext.asmetal.asmetaL.BasicTerm;
import org.xtext.asmetal.asmetaL.Term;
import org.xtext.asmetal.asmetaL.UpdateRule;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Update Rule</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.asmetal.asmetaL.impl.UpdateRuleImpl#getLocation <em>Location</em>}</li>
 *   <li>{@link org.xtext.asmetal.asmetaL.impl.UpdateRuleImpl#getUpdatingTerm <em>Updating Term</em>}</li>
 * </ul>
 *
 * @generated
 */
public class UpdateRuleImpl extends RuleImpl implements UpdateRule
{
  /**
   * The cached value of the '{@link #getLocation() <em>Location</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocation()
   * @generated
   * @ordered
   */
  protected BasicTerm location;

  /**
   * The cached value of the '{@link #getUpdatingTerm() <em>Updating Term</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUpdatingTerm()
   * @generated
   * @ordered
   */
  protected Term updatingTerm;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UpdateRuleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AsmetaLPackage.Literals.UPDATE_RULE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BasicTerm getLocation()
  {
    return location;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLocation(BasicTerm newLocation, NotificationChain msgs)
  {
    BasicTerm oldLocation = location;
    location = newLocation;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AsmetaLPackage.UPDATE_RULE__LOCATION, oldLocation, newLocation);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLocation(BasicTerm newLocation)
  {
    if (newLocation != location)
    {
      NotificationChain msgs = null;
      if (location != null)
        msgs = ((InternalEObject)location).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AsmetaLPackage.UPDATE_RULE__LOCATION, null, msgs);
      if (newLocation != null)
        msgs = ((InternalEObject)newLocation).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AsmetaLPackage.UPDATE_RULE__LOCATION, null, msgs);
      msgs = basicSetLocation(newLocation, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AsmetaLPackage.UPDATE_RULE__LOCATION, newLocation, newLocation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Term getUpdatingTerm()
  {
    return updatingTerm;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetUpdatingTerm(Term newUpdatingTerm, NotificationChain msgs)
  {
    Term oldUpdatingTerm = updatingTerm;
    updatingTerm = newUpdatingTerm;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AsmetaLPackage.UPDATE_RULE__UPDATING_TERM, oldUpdatingTerm, newUpdatingTerm);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUpdatingTerm(Term newUpdatingTerm)
  {
    if (newUpdatingTerm != updatingTerm)
    {
      NotificationChain msgs = null;
      if (updatingTerm != null)
        msgs = ((InternalEObject)updatingTerm).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AsmetaLPackage.UPDATE_RULE__UPDATING_TERM, null, msgs);
      if (newUpdatingTerm != null)
        msgs = ((InternalEObject)newUpdatingTerm).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AsmetaLPackage.UPDATE_RULE__UPDATING_TERM, null, msgs);
      msgs = basicSetUpdatingTerm(newUpdatingTerm, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AsmetaLPackage.UPDATE_RULE__UPDATING_TERM, newUpdatingTerm, newUpdatingTerm));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AsmetaLPackage.UPDATE_RULE__LOCATION:
        return basicSetLocation(null, msgs);
      case AsmetaLPackage.UPDATE_RULE__UPDATING_TERM:
        return basicSetUpdatingTerm(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AsmetaLPackage.UPDATE_RULE__LOCATION:
        return getLocation();
      case AsmetaLPackage.UPDATE_RULE__UPDATING_TERM:
        return getUpdatingTerm();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AsmetaLPackage.UPDATE_RULE__LOCATION:
        setLocation((BasicTerm)newValue);
        return;
      case AsmetaLPackage.UPDATE_RULE__UPDATING_TERM:
        setUpdatingTerm((Term)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AsmetaLPackage.UPDATE_RULE__LOCATION:
        setLocation((BasicTerm)null);
        return;
      case AsmetaLPackage.UPDATE_RULE__UPDATING_TERM:
        setUpdatingTerm((Term)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AsmetaLPackage.UPDATE_RULE__LOCATION:
        return location != null;
      case AsmetaLPackage.UPDATE_RULE__UPDATING_TERM:
        return updatingTerm != null;
    }
    return super.eIsSet(featureID);
  }

} //UpdateRuleImpl
