/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link AsmetaLWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractAsmetaLWebModule extends DefaultWebModule {

}
