/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AsmetaLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/asmetal/parser/antlr/internal/InternalAsmetaL.tokens");
	}
}
