/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bag Term</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.asmetal.asmetaL.BagTerm#getStart_term <em>Start term</em>}</li>
 *   <li>{@link org.xtext.asmetal.asmetaL.BagTerm#getOther_terms <em>Other terms</em>}</li>
 *   <li>{@link org.xtext.asmetal.asmetaL.BagTerm#getEnd_term <em>End term</em>}</li>
 *   <li>{@link org.xtext.asmetal.asmetaL.BagTerm#getStep <em>Step</em>}</li>
 * </ul>
 *
 * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getBagTerm()
 * @model
 * @generated
 */
public interface BagTerm extends CollectionTerm
{
  /**
   * Returns the value of the '<em><b>Start term</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start term</em>' containment reference.
   * @see #setStart_term(BasicTerm)
   * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getBagTerm_Start_term()
   * @model containment="true"
   * @generated
   */
  BasicTerm getStart_term();

  /**
   * Sets the value of the '{@link org.xtext.asmetal.asmetaL.BagTerm#getStart_term <em>Start term</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start term</em>' containment reference.
   * @see #getStart_term()
   * @generated
   */
  void setStart_term(BasicTerm value);

  /**
   * Returns the value of the '<em><b>Other terms</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.asmetal.asmetaL.BasicTerm}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Other terms</em>' containment reference list.
   * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getBagTerm_Other_terms()
   * @model containment="true"
   * @generated
   */
  EList<BasicTerm> getOther_terms();

  /**
   * Returns the value of the '<em><b>End term</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End term</em>' containment reference.
   * @see #setEnd_term(ConstantTerm)
   * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getBagTerm_End_term()
   * @model containment="true"
   * @generated
   */
  ConstantTerm getEnd_term();

  /**
   * Sets the value of the '{@link org.xtext.asmetal.asmetaL.BagTerm#getEnd_term <em>End term</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End term</em>' containment reference.
   * @see #getEnd_term()
   * @generated
   */
  void setEnd_term(ConstantTerm value);

  /**
   * Returns the value of the '<em><b>Step</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Step</em>' containment reference.
   * @see #setStep(ConstantTerm)
   * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getBagTerm_Step()
   * @model containment="true"
   * @generated
   */
  ConstantTerm getStep();

  /**
   * Sets the value of the '{@link org.xtext.asmetal.asmetaL.BagTerm#getStep <em>Step</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Step</em>' containment reference.
   * @see #getStep()
   * @generated
   */
  void setStep(ConstantTerm value);

} // BagTerm
