/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean Domain</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getBooleanDomain()
 * @model
 * @generated
 */
public interface BooleanDomain extends StandardDomain
{
} // BooleanDomain
