/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Conditional Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.asmetal.asmetaL.ConditionalRule#getGuard <em>Guard</em>}</li>
 *   <li>{@link org.xtext.asmetal.asmetaL.ConditionalRule#getThenRule <em>Then Rule</em>}</li>
 *   <li>{@link org.xtext.asmetal.asmetaL.ConditionalRule#getElseRule <em>Else Rule</em>}</li>
 * </ul>
 *
 * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getConditionalRule()
 * @model
 * @generated
 */
public interface ConditionalRule extends BasicRule
{
  /**
   * Returns the value of the '<em><b>Guard</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Guard</em>' containment reference.
   * @see #setGuard(Term)
   * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getConditionalRule_Guard()
   * @model containment="true"
   * @generated
   */
  Term getGuard();

  /**
   * Sets the value of the '{@link org.xtext.asmetal.asmetaL.ConditionalRule#getGuard <em>Guard</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Guard</em>' containment reference.
   * @see #getGuard()
   * @generated
   */
  void setGuard(Term value);

  /**
   * Returns the value of the '<em><b>Then Rule</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then Rule</em>' containment reference.
   * @see #setThenRule(Rule)
   * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getConditionalRule_ThenRule()
   * @model containment="true"
   * @generated
   */
  Rule getThenRule();

  /**
   * Sets the value of the '{@link org.xtext.asmetal.asmetaL.ConditionalRule#getThenRule <em>Then Rule</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Then Rule</em>' containment reference.
   * @see #getThenRule()
   * @generated
   */
  void setThenRule(Rule value);

  /**
   * Returns the value of the '<em><b>Else Rule</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else Rule</em>' containment reference.
   * @see #setElseRule(Rule)
   * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getConditionalRule_ElseRule()
   * @model containment="true"
   * @generated
   */
  Rule getElseRule();

  /**
   * Sets the value of the '{@link org.xtext.asmetal.asmetaL.ConditionalRule#getElseRule <em>Else Rule</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Else Rule</em>' containment reference.
   * @see #getElseRule()
   * @generated
   */
  void setElseRule(Rule value);

} // ConditionalRule
