/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Domain Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.asmetal.asmetaL.DomainDefinition#getDefinedDomainName <em>Defined Domain Name</em>}</li>
 *   <li>{@link org.xtext.asmetal.asmetaL.DomainDefinition#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getDomainDefinition()
 * @model
 * @generated
 */
public interface DomainDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Defined Domain Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Defined Domain Name</em>' attribute.
   * @see #setDefinedDomainName(String)
   * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getDomainDefinition_DefinedDomainName()
   * @model
   * @generated
   */
  String getDefinedDomainName();

  /**
   * Sets the value of the '{@link org.xtext.asmetal.asmetaL.DomainDefinition#getDefinedDomainName <em>Defined Domain Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Defined Domain Name</em>' attribute.
   * @see #getDefinedDomainName()
   * @generated
   */
  void setDefinedDomainName(String value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(Term)
   * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getDomainDefinition_Body()
   * @model containment="true"
   * @generated
   */
  Term getBody();

  /**
   * Sets the value of the '{@link org.xtext.asmetal.asmetaL.DomainDefinition#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(Term value);

} // DomainDefinition
