/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Extend Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.asmetal.asmetaL.ExtendRule#getExtendedDomain <em>Extended Domain</em>}</li>
 *   <li>{@link org.xtext.asmetal.asmetaL.ExtendRule#getBoundVar <em>Bound Var</em>}</li>
 *   <li>{@link org.xtext.asmetal.asmetaL.ExtendRule#getDoRule <em>Do Rule</em>}</li>
 * </ul>
 *
 * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getExtendRule()
 * @model
 * @generated
 */
public interface ExtendRule extends BasicRule
{
  /**
   * Returns the value of the '<em><b>Extended Domain</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Extended Domain</em>' containment reference.
   * @see #setExtendedDomain(Domain)
   * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getExtendRule_ExtendedDomain()
   * @model containment="true"
   * @generated
   */
  Domain getExtendedDomain();

  /**
   * Sets the value of the '{@link org.xtext.asmetal.asmetaL.ExtendRule#getExtendedDomain <em>Extended Domain</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Extended Domain</em>' containment reference.
   * @see #getExtendedDomain()
   * @generated
   */
  void setExtendedDomain(Domain value);

  /**
   * Returns the value of the '<em><b>Bound Var</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.asmetal.asmetaL.VariableTerm}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bound Var</em>' containment reference list.
   * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getExtendRule_BoundVar()
   * @model containment="true"
   * @generated
   */
  EList<VariableTerm> getBoundVar();

  /**
   * Returns the value of the '<em><b>Do Rule</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Do Rule</em>' containment reference.
   * @see #setDoRule(Rule)
   * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getExtendRule_DoRule()
   * @model containment="true"
   * @generated
   */
  Rule getDoRule();

  /**
   * Sets the value of the '{@link org.xtext.asmetal.asmetaL.ExtendRule#getDoRule <em>Do Rule</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Do Rule</em>' containment reference.
   * @see #getDoRule()
   * @generated
   */
  void setDoRule(Rule value);

} // ExtendRule
