/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Invariant Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.asmetal.asmetaL.InvariantElement#getConstrainedName <em>Constrained Name</em>}</li>
 *   <li>{@link org.xtext.asmetal.asmetaL.InvariantElement#getDomainList <em>Domain List</em>}</li>
 * </ul>
 *
 * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getInvariantElement()
 * @model
 * @generated
 */
public interface InvariantElement extends EObject
{
  /**
   * Returns the value of the '<em><b>Constrained Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constrained Name</em>' attribute.
   * @see #setConstrainedName(String)
   * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getInvariantElement_ConstrainedName()
   * @model
   * @generated
   */
  String getConstrainedName();

  /**
   * Sets the value of the '{@link org.xtext.asmetal.asmetaL.InvariantElement#getConstrainedName <em>Constrained Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constrained Name</em>' attribute.
   * @see #getConstrainedName()
   * @generated
   */
  void setConstrainedName(String value);

  /**
   * Returns the value of the '<em><b>Domain List</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.asmetal.asmetaL.Domain}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Domain List</em>' containment reference list.
   * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getInvariantElement_DomainList()
   * @model containment="true"
   * @generated
   */
  EList<Domain> getDomainList();

} // InvariantElement
