/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Iterative While Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getIterativeWhileRule()
 * @model
 * @generated
 */
public interface IterativeWhileRule extends TurboDerivedRule
{
} // IterativeWhileRule
