/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Local Function</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getLocalFunction()
 * @model
 * @generated
 */
public interface LocalFunction extends DynamicFunction
{
} // LocalFunction
