/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sequence CT</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getSequenceCT()
 * @model
 * @generated
 */
public interface SequenceCT extends ComprehensionTerm
{
} // SequenceCT
