/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Standard Domain</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getStandardDomain()
 * @model
 * @generated
 */
public interface StandardDomain extends BasicTD
{
} // StandardDomain
