/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Structured TD</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getStructuredTD()
 * @model
 * @generated
 */
public interface StructuredTD extends TypeDomain
{
} // StructuredTD
