/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Term As Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.asmetal.asmetaL.TermAsRule#getTerm <em>Term</em>}</li>
 *   <li>{@link org.xtext.asmetal.asmetaL.TermAsRule#getParameters <em>Parameters</em>}</li>
 * </ul>
 *
 * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getTermAsRule()
 * @model
 * @generated
 */
public interface TermAsRule extends Rule
{
  /**
   * Returns the value of the '<em><b>Term</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Term</em>' containment reference.
   * @see #setTerm(BasicTerm)
   * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getTermAsRule_Term()
   * @model containment="true"
   * @generated
   */
  BasicTerm getTerm();

  /**
   * Sets the value of the '{@link org.xtext.asmetal.asmetaL.TermAsRule#getTerm <em>Term</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Term</em>' containment reference.
   * @see #getTerm()
   * @generated
   */
  void setTerm(BasicTerm value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.asmetal.asmetaL.Term}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getTermAsRule_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<Term> getParameters();

} // TermAsRule
