/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Turbo Local State Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.asmetal.asmetaL.TurboLocalStateRule#getLocalFunction <em>Local Function</em>}</li>
 *   <li>{@link org.xtext.asmetal.asmetaL.TurboLocalStateRule#getInit <em>Init</em>}</li>
 *   <li>{@link org.xtext.asmetal.asmetaL.TurboLocalStateRule#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getTurboLocalStateRule()
 * @model
 * @generated
 */
public interface TurboLocalStateRule extends TurboRule
{
  /**
   * Returns the value of the '<em><b>Local Function</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.asmetal.asmetaL.LocalFunction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Local Function</em>' containment reference list.
   * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getTurboLocalStateRule_LocalFunction()
   * @model containment="true"
   * @generated
   */
  EList<LocalFunction> getLocalFunction();

  /**
   * Returns the value of the '<em><b>Init</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.asmetal.asmetaL.Rule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Init</em>' containment reference list.
   * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getTurboLocalStateRule_Init()
   * @model containment="true"
   * @generated
   */
  EList<Rule> getInit();

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(Rule)
   * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getTurboLocalStateRule_Body()
   * @model containment="true"
   * @generated
   */
  Rule getBody();

  /**
   * Sets the value of the '{@link org.xtext.asmetal.asmetaL.TurboLocalStateRule#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(Rule value);

} // TurboLocalStateRule
