/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.asmetaL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Turbo Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.asmetal.asmetaL.AsmetaLPackage#getTurboDeclaration()
 * @model
 * @generated
 */
public interface TurboDeclaration extends RuleDeclaration
{
} // TurboDeclaration
