/*
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.asmetal.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAsmetaLScopeProvider extends DelegatingScopeProvider {
}
